create tutorial docker
railsgirls/guides-ptbr pull request #122
Opened 2021-04-06 10:07 UTC by hemershon

I created a small docker tutorial to teach people who want to use the docker and docker-compose to work with rails

2021-04-11 08:11 UTC, anaschwendler requested changes
Oi @hemershon! 🚀 

Tudo bom? Muito obrigada por sua contribuição, já está bem interessante, só tem algumas coisas que eu gostaria de comentar sobre o que foi feito.

Em geral, nós usamos o markdown de uma forma um pouco estilizada para facilitar o uso pra quem está começando, temos alguns highlights para facilitar a identificação de onde vamos aplicar o código:
Terminal:

```
{% highlight sh %}
exemplo de código
{% endhighlight %}
```

Fica assim:
![image](https://user-images.githubusercontent.com/4131432/114296871-d2b48e00-9aad-11eb-8a5c-0fa5689d3a12.png)

No `erb`:
```
{% highlight erb %}
```

Fica assim:
![image](https://user-images.githubusercontent.com/4131432/114296884-e233d700-9aad-11eb-9ee2-5e4329a85420.png)

Você poderia alterar sua postagem para esse padrão?
Falamos disso nessa parte: https://github.com/railsgirls/guides-ptbr#pygments-e-code-highlighting

Também, se puder mudar a branch para o qual quer adicionar o PR para master, é como fazemos por aqui.
Depois que tudo está ok na master, eu faço merge ao `gh-pages`

Muito obrigada!

2021-04-11 08:11 UTC, anaschwendler commented on _posts/2021-04-05-docker.markdown
> +Docker instalado na sua maquina [Instalação do docker](https://docs.docker.com/get-docker/)
Aqui eu achei bem interessante o fato de usar a documentação oficial, mas eu fico pensando que talvez fosse interessante se a gente pudesse achar alguma documentação oficial em português, isso facilita pra quem não entende inglês nível profissional ainda :)

2021-04-11 08:11 UTC, anaschwendler commented on _posts/2021-04-05-docker.markdown
> +Comece configurando os arquivos necessários para construir o aplicativo que será executado dentro de um [contêiner](https://www.redhat.com/pt-br/topics/containers/what-is-docker) do Docker suas depen
Aqui com a referência em português ficou ótimo! 💯

2021-04-11 08:11 UTC, anaschwendler commented on _posts/2021-04-05-docker.markdown
> +Primeiro, o Compose cria a imagem para o webserviço usando o Dockerfile. O --no-depsdiz ao Compose para não iniciar os serviços vinculados. Em seguida, ele é executado rails newdentro de um novo cont
Aqui tem um pequeno erro de digitação: 

O `--no-deps` diz

2021-05-15 11:58 UTC, hemershon commented on _posts/2021-04-05-docker.markdown
> +*Traduzido por [Hemershon Silva](https://hemershon.com/)*
anaschwendler vou arrumar

2021-05-15 11:59 UTC, hemershon commented on _posts/2021-04-05-docker.markdown
> +Docker instalado na sua maquina [Instalação do docker](https://docs.docker.com/get-docker/)
anaschwendler vou arrumar

2021-05-15 11:59 UTC, hemershon commented on _posts/2021-04-05-docker.markdown
> +Comece configurando os arquivos necessários para construir o aplicativo que será executado dentro de um [contêiner](https://www.redhat.com/pt-br/topics/containers/what-is-docker) do Docker suas depen
anaschwendler vou arrumar

2021-05-15 11:59 UTC, hemershon commented on _posts/2021-04-05-docker.markdown
> +Primeiro, o Compose cria a imagem para o webserviço usando o Dockerfile. O --no-depsdiz ao Compose para não iniciar os serviços vinculados. Em seguida, ele é executado rails newdentro de um novo cont
**anaschwendler vou arrumar**

2021-07-21 08:51 UTC, merged

2021-07-21 08:52 UTC, anaschwendler commented
Vou fechar esse PR em razão de #127